"""add admin fields and knowledge sources

Revision ID: 59130777a9fb
Revises: 837dafc05cd8
Create Date: 2026-09-30 15:45:00.360992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59130777a9fb'
down_revision: Union[str, Sequence[str], None] = '837dafc05cd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_active', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_active')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
